import { IOTOSettings } from "../src/types";
import { t } from "../lang/helpers";

export const DEFAULT_SETTINGS: IOTOSettings = {
	inputFolder: t("1-Inputs"),
	outputFolder: t("2-Outputs"),
	taskFolder: t("3-Tasks"),
	outcomeFolder: t("4-Outcomes"),
	extraFolder: t("0-Extras"),
	userTemplatePrefix: "My",
	IOTOFrameworkPath: t("0-Extras/IOTO"),
	LTDListInputSectionHeading: t("Input (LEARN)"),
	LTDListOutputSectionHeading: t("Output (THINK)"),
	LTDListOutcomeSectionHeading: t("Outcome (DO)"),
	useUserTemplate: true,
	IOTOMovieTimeTags: "MT1,MT2,MT3,MT4",
	addLinkToCurrentTDL: true,
	defaultTDLDateFormat: "YYYY-MM-DD",
	projectNameFormat: "lastDash",
	inputSelectorExcludesPaths: "",
	outputSelectorExcludesPaths: "",
	taskSelectorExcludesPaths: "",
	outcomeSelectorExcludesPaths: "",
	inputSelectorShowOptionOrder: true,
	outputSelectorShowOptionOrder: true,
	taskSelectorShowOptionOrder: true,
	outcomeSelectorShowOptionOrder: true,
	inputSelectorShowBasePath: false,
	outputSelectorShowBasePath: false,
	taskSelectorShowBasePath: false,
	outcomeSelectorShowBasePath: false,
	inputSelectorFolderOptionTemplate: t("Create Input Notes In {{folder}}"),
	outputSelectorFolderOptionTemplate: t("Create Output Notes In {{folder}}"),
	taskSelectorFolderOptionTemplate: t("Create TDL In {{folder}}"),
	outcomeSelectorFolderOptionTemplate: t(
		"Create Outcome Notes In {{folder}}"
	),
	outcomeSelectorIncludeParentFolder: true,
	outcomeProjectDefaultSubFolders: t("Articles\nSummary"),
	newInputNoteFollowUpAction: "0",
	newOutputNoteFollowUpAction: "0",
	newOutcomeNoteFollowUpAction: "0",
	taskSelectorEnableFutureDaysChoices: false,
	taskSelectorUseCustomTdlNames: false,
	fleetingNotePrefix: t("Fleeting Notes"),
	fleetingNoteDateFormat: "YYYY-MM-DD",
	inputNoteNamePrefix: "",
	inputNoteNamePostfix: "",
	inputNoteDefaultExcalidrawTemplate: "",
	outputNoteNamePrefix: "",
	outputNoteNamePostfix: "",
	outputNoteDefaultExcalidrawTemplate: "",
	outcomeNoteNamePrefix: "",
	outcomeNoteNamePostfix: "",
	outcomeNoteDefaultExcalidrawTemplate: "",
	defaultTDLHeadingLevel: "##",
	templaterDataPath: "plugins/templater-obsidian/data.json",
	hotkeysFile: "hotkeys.json",
	workspacesFile: "workspaces.json",
	projectNameSource: "first",
	newInputNoteAddedToTDLFollowUpAction: "0",
	newOutputNoteAddedToTDLFollowUpAction: "0",
	newOutcomeNoteAddedToTDLFollowUpAction: "0",
	inputFolderDefaultSubFolders: t("Resources\nQuickNotes"),
	outputFolderDefaultSubFolders: t("FleetingNotes\nCardNotes"),
	defaultProjects: t("LearnIOTO\nLearnAI"),
	iotoUtilsSnRRulesFolder: t("SearchAndReplaceRules"),
	iotoUtilsQuickImageSize: "1920x1080\n900x600\n600x400",
	iotoUtilsQuickImageMask: true,
	iotoUtilsTemplateSnippetFolder: t("TemplatesSnippets"),
	iotoUtilsPropertyManagementFolder: t("PropertyManagement"),
	iotoUtilsQuickBlockTypes: t("QuickBlockTypes"),
	iotoUtilsQuickBlockIdDateFormat: "YYYY-MM-DD",
	iotoUtilsQuickBlockIdUseSingleLineAsSeparator: false,
	airtableAPIKeyForSync: "",
	airtableBaseIDForSync: "",
	airtableTableIDForSync: "",

	airtableAPIKeyForFetch: "",
	airtableBaseIDForFetch: "",
	airtableTableIDForFetch: "",

	vikaAPIKeyForSync: "",
	vikaTableIDForSync: "",

	vikaAPIKeyForFetch: "",
	vikaTableIDForFetch: "",

	feishuAppIDForSync: "",
	feishuAppSecretForSync: "",
	feishuBaseIDForSync: "",
	feishuTableIDForSync: "",

	feishuAppIDForFetch: "",
	feishuAppSecretForFetch: "",
	feishuBaseIDForFetch: "",
	feishuTableIDForFetch: "",
};
